# Site Configuration
repository: koushikhathwar/portfolio
favicon: images/favicon.ico

# Content Configuration Version
version: 2

# Personal Info
name: Koushik Hathwar
title: Cloud DevOps Engineer
email: koushik.hathwar@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social Links
github_username: koushikhathwar
instagram_username: hathwarkoushik
linkedin_username: koushik-hathwar-b4020973
orcid_username: 0000-0003-4708-6596
google_analytics: G-2CXJMFFB28
gtag: G-2CXJMFFB28

# Additional Links
additional_links:
  - title: Medium Profile
    icon: fab fa-medium
    url: https://medium.com/@koushik.hathwar

# About Section
about_profile_image: images/profile.jpg
about_content: | 
  "Hey there, I'm Koushik Hathwar ðŸ‘‹. Nice to meet you!"  
  Iâ€™m a Cloud Developer with over 4 years of experience, currently specializing in DevOps. I am pursuing an MS in Cloud DevOps at ATU Donegal. I enjoy creating Infrastructure as Code (IaC) and cloud infrastructure UI that is efficient, user-friendly, and enjoyable.

  I have experience with a wide range of tools and frameworks and constantly seek opportunities to explore new ones. My core expertise includes:  
  **Azure**, **AWS**, **Git**, **Kubernetes**, **Docker**, **Jenkins**, **React & Redux**, **Node.js**, **Python**, **MySQL**, **IaC**, and **PaaS**.  

  I excel in: **AWS**, **Azure**, and **ðŸ•**.

# Content
content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        title: Super Awesome Project
        link: https://github.com/koushikhathwar
        additional_links:
          - title: koushikhathwar/portfolio
            icon: fab fa-github
            url: https://github.com/koushikhathwar/portfolio
        quote: >
          A modern, simple static resume template and theme powered by Jekyll and GitHub Pages.
        description: |
          I started this project as a way to learn **React**, and it has since grown into a fully-fledged application.  
          Through this project, I gained many skills and am proud to include it in my portfolio. If you don't have a project as cool as this, I highly recommend starting one!

  - title: Experience
    layout: list
    content:
      - layout: left
        border: weak
        title: Mindtree (L&T Company)
        link: https://www.ltimindtree.com
        sub_title: Senior Software Engineer
        caption: March 2021 - August 2022
        quote: >
          Tackling 21st-century challenges through innovative cloud configurations.
        description: |
          Played a key role in managing cloud infrastructure for a commercial IoT platform.  
          - Transformed on-premises systems into modular cloud applications using **microservices**.  
          - Designed and maintained CI/CD pipelines, driving innovation within a 20-member team.  
          - Streamlined workflows and ensured scalability across multiple platforms.

      - layout: left
        border: weak
        title: IISc India
        link: https://www.iisc.ac.in
        sub_title: Research Assistant
        caption: February 2020 - March 2021
        quote: >
          IISc remains one of India's premier institutions for cutting-edge research and innovation.
        description: |
          - Designed and implemented SaaS solutions using **Azure** services.  
          - Developed CI/CD pipelines and monitored **Azure Microservices** for performance optimization.  
          - Gained expertise in **Azure IoT Hub**, **Event Hubs**, and **Power BI**.

  - title: Education
    layout: list
    content:
      - layout: left
        border: weak
        title: ATU Donegal
        caption: 2023
        sub_title: MS in DevOps
        link: https://www.lyit.ie
        quote: >
          ATU Donegal fosters one of the most progressive learning environments in Ireland.
        description: |
          Learned teamwork and time management while balancing academics and extracurricular activities.  
          Vice-President of the **ATU Table Tennis Club**, fostering community engagement.

      - layout: left
        border: weak
        title: VTU India
        caption: 2017
        sub_title: BE in Computer Science
        link: https://www.vvce.ac.in
        quote: >
          VTU excels in engineering education and technical research across India.
        description: |
          Co-founded a tech company, **Techambush**, focusing on web design and social media promotions.  
          - Enhanced project management skills through leadership roles in the entrepreneurship society.

  - title: When I'm Not Programming
    layout: text
    content: |
      When Iâ€™m not programming, I enjoy exploring the outdoors through hiking, cycling, and cricket.  
      Iâ€™m passionate about abstract photography and sharing my work on [Instagram](https://www.instagram.com/hathwarkoushik/).  
      Additionally, I love watching Formula 1 and spending time with my two dogs.

# Footer
footer_show_references: false

# Build Settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
